#!/bin/bash
set -e

# Force locale to ensure consistent sorting
export LC_ALL=C

cd "$(dirname "$0")"/..
files=( hashes/lol/hashes.*.txt )

# Declare and fill variable with csplit patterns
#   declare_csplit_patterns VARNAME HASHSIZE "PATTERNS..."
declare_csplit_patterns() {
  declare -n varname="$1"; shift
  local hashsize="$1"; shift
  varname=()
  for pat in $*; do
    varname+=("/^.\{$hashsize\} ${pat//\//\\/}/")
  done
}

declare_csplit_patterns hashes_games_split_patterns 16 "
  assets/characters/f
  assets/characters/l
  assets/characters/p
  assets/characters/s
  assets/characters/tft
  assets/characters/thresh
  assets/loot/
  assets/sounds/
"

# Make sure to update merged files atomically, in case they are used by other processes
# Don't bother for split files as they are only used for repo maintenance
for f in "${files[@]}"; do
  ftmp="$f.tmp-prepare"
  trap 'rm -f "$ftmp"' EXIT
  # Merge everything, to avoid losing hashes
  cat "$f" "$f".[0-9] 2>/dev/null | sort -u -k 2 -o "$ftmp"
  mv "$ftmp" "$f"
  trap - EXIT

  # Split files that are too big
  rm -f "$f".[0-9]
  case "$f" in
    hashes/lol/hashes.game.txt)
      csplit -s -n 1 -f "$f." "$f" "${hashes_games_split_patterns[@]}" ;;
  esac
done
